theme = "noctalia"

[editor]
line-number = "relative"
scroll-lines = 1
auto-pairs = true
bufferline = "always"
auto-format = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.lsp]
display-messages = true

[keys.normal]
g = { a = "code_action" }
ret = ["move_line_down", "goto_first_nonwhitespace"]
X = "extend_line_above"
D = "delete_char_backward"
"[" = { b = ":bp" }
"]" = { b = ":bn" }
H = ":bp"
L = ":bn"
"C-S-B" = ":sh just build"
"C-S-R" = ":sh just run"

[keys.normal.space]
q = ":wbc"
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true"
]
G = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all"
]
