{ self, inputs, ... }:
{
  flake.nixosModules.vintageserver =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    {
      virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
      };

      networking.firewall.interfaces =
        let
          matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
        in
        {
          "${matchAll}".allowedUDPPorts = [ 53 ];
        };

      virtualisation.oci-containers.backend = "podman";

      virtualisation.oci-containers.containers."vintagestory-server" = {
        image = "ghcr.io/darkmatterproductions/vintagestory:latest";
        environment = {
          "ENABLE_DEBUG_LOGGING" = "true";
          "VS_CFG_MAX_CLIENTS" = "32";
          "VS_CFG_SERVER_IP" = "0.0.0.0";
          "VS_CFG_SERVER_NAME" = "The Toadstool";
          "VS_CFG_SERVER_PASSWORD" = "WelcomeToTheToadstool!";
          "VS_CFG_SERVER_UPNP" = "true";
        };
        volumes = [
          "/home/sysop/vintagestory/data:/vintagestory/data:rw"
        ];
        ports = [
          "42420:42420/tcp"
          "42420:42420/udp"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=vintagestory"
          "--network=toadstool-vs-server_default"
        ];
      };
      systemd.services."podman-vintagestory-server" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-toadstool-vs-server_default.service"
        ];
        requires = [
          "podman-network-toadstool-vs-server_default.service"
        ];
        partOf = [
          "podman-compose-toadstool-vs-server-root.target"
        ];
        wantedBy = [
          "podman-compose-toadstool-vs-server-root.target"
        ];
      };

      systemd.services."podman-network-toadstool-vs-server_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f toadstool-vs-server_default";
        };
        script = ''
          podman network inspect toadstool-vs-server_default || podman network create toadstool-vs-server_default
        '';
        partOf = [ "podman-compose-toadstool-vs-server-root.target" ];
        wantedBy = [ "podman-compose-toadstool-vs-server-root.target" ];
      };

      systemd.targets."podman-compose-toadstool-vs-server-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };
    };
}
